### ISSUE TITLE
Why does it require Quilt?

### ISSUE THREAD

**Issue by Secret-chest** [Queerbric/Inspecio#88]
I loved this mod. Now that I am updating to 1.19, I see thet you switched to "Quilt". WHY?

I am using FO BTW.

**Comment by AurySystem** [comment]
Better api, less people constantly breaking everything with cursed overwritting mixins, a modloader that's actually community focused. It's a better question to ask why wouldn't it be on quiltloader.
quilt can run fabric mods anyways.

**Comment by Secret-chest** [comment]
> Better api, less people constantly breaking everything with cursed overwritting mixins, a modloader that's actually community focused. It's a better question to ask why wouldn't it be on quiltloader.
> quilt can run fabric mods anyways.

I use FO modpack...

**Comment by Secret-chest** [comment]
And why did you need to switch?

**Comment by Secret-chest** [comment]
What's wrong with Fabric?

**Comment by LemmaEOF** [comment]
The things Inspecio does are *quite literally* impossible with Fabric API. Fabric API's tooltip system just does not allow doing what Inspecio does, so it has to use Quilt's API which *does* allow it.

**Comment by LambdAurora** [comment]
> The things Inspecio does are _quite literally_ impossible with Fabric API. Fabric API's tooltip system just does not allow doing what Inspecio does, so it has to use Quilt's API which _does_ allow it.

Er, almost, the way Fabric does tags is slightly more annoying but not unworkable.
The bigger issue lies in the client tags of the mods, for which the API literally does not exist at all in Fabric.
And some other stuff might use more Quilt-only APIs in the future.

**Comment by NebelNidas** [comment]
@LambdAurora While there are a few things Quilt makes easier, yes, it's not to the extent that would justify going Quilt-only (unless one of your goals is to push people to the new ecosystem, which I think holds true for you, as a Quilt dev). Nothing personal, I can understand that. Though, until Quilt becomes the default, I'd like to have a Fabric version of this mod, which is why I've ported the last non-quiltified version of Inspecio to 1.19, and I intend to keep it up to date with upstream as good as possible: https://github.com/ReviversMC/inspecio-fabric
It's missing the client side tag recognition, but I'll implement it as soon as the corresponding API is merged into Fabric API: https://github.com/FabricMC/fabric/pull/2308

Now, my question is, should I create separate, new CurseForge/Modrinth projects (labeled "Inspecio (Fabric)" or something along the lines)? Or would you be OK with uploading this Fabric version to the existing pages?

**Comment by LambdAurora** [comment]
So, the client side tag stuff won't work with Fabric's stuff anyway since what Inspecio uses is client default, still using server sync

And for the fork, please use an entirely new name, I am not willing to have Fabric JARs on the existing projects and I am not very comfortable with it using the same name.

**Comment by NebelNidas** [comment]
>  I am not willing to have Fabric JARs on the existing projects

Understandable

> I am not very comfortable with it using the same name

Well, it's the same exact mod, only for Fabric instead of Quilt (and one missing feature that's going to be added later), so it makes sense to keep the name. I will of course add a right-in-your-face disclaimer that we're not directly affiliated and bugs shouldn't be reported to you

**Comment by LambdAurora** [comment]
> Well, it's the same exact mod, only for Fabric instead of Quilt (and one missing feature that's going to be added later), so it makes sense to keep the name. I will of course add a right-in-your-face disclaimer that we're not directly affiliated and bugs shouldn't be reported to you

Even then, if you look at all the sodium Forge ports, none of them is called Sodium due to Jelly asking for them to use a different name, which I am doing right now.

**Comment by NebelNidas** [comment]
Meh, if you absolutely insist on it, alright. Although you can't really compare Sodium ports (which have to be rewritten from the ground up and can't be made compatible with Forge either way) to the small changes I'm making. I guess this decision also applies to the project icon?

**Comment by LambdAurora** [comment]
Yeah, using a different project icon would be appreciated.

And it can be compared to Sodium ports:
 - it's a port to a platform the author doesn't support/like
 - it's loosing features through porting, even if it's seen as minimal here to me it's not something I appreciate
